### PR TITLE
Add `restrictTo` option

### PR DESCRIPTION
**Pull request by giuseppeg**
This option allows to convert a restricted set of pseudo classes.

### CODE REVIEW

**Comment by giuseppeg** [comment]
@SlexAxton this is the branch I was talking about :neckbeard:

**Comment by squidfunk** [comment]
Any updates on this? Can this be released?

**Comment by alex-stripe** [comment]
Not my lib, but since I seem to be implicated here a bit. I'm :+1:

**Comment by giuseppeg** [comment]
@squidfunk @grouchal published 0.2.0

**Comment by squidfunk** [comment]
Awesome, thank!

**Pull request merged**
