### PR TITLE
Remove dublicate lock file

### PR DESCRIPTION
**Pull request by ai**
Right now project has 2 lock files. I keep only yarn (or could keep npm if you want, but I personally think pnpm is faster and more user-friendly).

### CODE REVIEW

**Review by giuseppeg — COMMENTED** [review]
Frankly I don't know how to behave in these circumstances. My gut feeling is that a package should include all the lock files so that dependencies are locked regardless of which package manager you use

**Comment by ai** [comment]
> My gut feeling is that a package should include all the lock files so that dependencies are locked regardless of which package manager you use

It is interesting idea but doesn’t work on practice without special tools.

Right now `yarn.lock` and `package-lock.json` just have different versions.

**Comment by giuseppeg** [comment]
I am trying to learn more about this

> doesn’t work on practice

Why? I am trying to learn more about this. Won't npm use package-lock.json, yarn yarn.lock etc.?

**Comment by ai** [comment]
> Why? I am trying to learn more about this. Won't npm use package-lock.json, yarn yarn.lock etc.?

Yes. The problem is that it is very easy to forget update another lock file on dependency install or update.

You need some tool to keep them in sync.

**Comment by giuseppeg** [comment]
Ah sure, but this could be a git action or something. Anyway I don't really mind. Probably we can shipt whatever is more popular or you prefer and remove the others.

**Comment by ai** [comment]
> Probably we can shipt whatever is more popular

In this case `package-lock.json`. I will update PR.

**Comment by ai** [comment]
@giuseppeg Done. I removed yarn.

**Review by giuseppeg — APPROVED** [review]

**Pull request merged**
